"""monday blue

Revision ID: 0597a62d7f4c
Revises: b58a62629150
Create Date: 2019-08-19 15:32:10.334570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0597a62d7f4c'
down_revision = 'b58a62629150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transmissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('vehicles', sa.Column('engine_size', sa.String(length=80), nullable=True))
    op.add_column('vehicles', sa.Column('fuel_type_id', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('transmission_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_vehicles_engine_size'), 'vehicles', ['engine_size'], unique=False)
    op.create_index(op.f('ix_vehicles_fuel_type_id'), 'vehicles', ['fuel_type_id'], unique=False)
    op.create_foreign_key(None, 'vehicles', 'fuel_types', ['fuel_type_id'], ['id'])
    op.create_foreign_key(None, 'vehicles', 'transmissions', ['transmission_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_index(op.f('ix_vehicles_fuel_type_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_engine_size'), table_name='vehicles')
    op.drop_column('vehicles', 'transmission_id')
    op.drop_column('vehicles', 'fuel_type_id')
    op.drop_column('vehicles', 'engine_size')
    op.drop_table('transmissions')
    op.drop_table('fuel_types')
    # ### end Alembic commands ###
