"""empty message

Revision ID: 0a0636243e8a
Revises: 
Create Date: 2019-08-20 14:34:10.590618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a0636243e8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transmissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('features_association',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('feature_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('features', sa.Column('name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_features_name'), 'features', ['name'], unique=False)
    op.add_column('vehicles', sa.Column('area', sa.String(length=80), nullable=True))
    op.add_column('vehicles', sa.Column('engine_size', sa.String(length=80), nullable=True))
    op.add_column('vehicles', sa.Column('fuel_type_id', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('interior', sa.String(length=80), nullable=True))
    op.add_column('vehicles', sa.Column('phone_number', sa.String(length=80), nullable=True))
    op.add_column('vehicles', sa.Column('seller_email', sa.String(length=80), nullable=True))
    op.add_column('vehicles', sa.Column('seller_name', sa.String(length=80), nullable=True))
    op.add_column('vehicles', sa.Column('transmission_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_vehicles_area'), 'vehicles', ['area'], unique=False)
    op.create_index(op.f('ix_vehicles_condition'), 'vehicles', ['condition'], unique=False)
    op.create_index(op.f('ix_vehicles_engine_size'), 'vehicles', ['engine_size'], unique=False)
    op.create_index(op.f('ix_vehicles_fuel_type_id'), 'vehicles', ['fuel_type_id'], unique=False)
    op.create_index(op.f('ix_vehicles_interior'), 'vehicles', ['interior'], unique=False)
    op.create_index(op.f('ix_vehicles_phone_number'), 'vehicles', ['phone_number'], unique=False)
    op.create_index(op.f('ix_vehicles_seller_email'), 'vehicles', ['seller_email'], unique=False)
    op.create_index(op.f('ix_vehicles_seller_name'), 'vehicles', ['seller_name'], unique=False)
    op.create_foreign_key(None, 'vehicles', 'fuel_types', ['fuel_type_id'], ['id'])
    op.create_foreign_key(None, 'vehicles', 'transmissions', ['transmission_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_index(op.f('ix_vehicles_seller_name'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_seller_email'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_phone_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_interior'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_fuel_type_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_engine_size'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_condition'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_area'), table_name='vehicles')
    op.drop_column('vehicles', 'transmission_id')
    op.drop_column('vehicles', 'seller_name')
    op.drop_column('vehicles', 'seller_email')
    op.drop_column('vehicles', 'phone_number')
    op.drop_column('vehicles', 'interior')
    op.drop_column('vehicles', 'fuel_type_id')
    op.drop_column('vehicles', 'engine_size')
    op.drop_column('vehicles', 'area')
    op.drop_index(op.f('ix_features_name'), table_name='features')
    op.drop_column('features', 'name')
    op.drop_table('features_association')
    op.drop_table('transmissions')
    op.drop_table('fuel_types')
    # ### end Alembic commands ###
