"""new images3

Revision ID: 24ca0775c66f
Revises: 4234ad301976
Create Date: 2019-08-14 17:34:44.066815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ca0775c66f'
down_revision = '4234ad301976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vehicles_name', table_name='vehicles')
    op.drop_column('vehicles', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index('ix_vehicles_name', 'vehicles', ['name'], unique=False)
    # ### end Alembic commands ###
