"""monday blues

Revision ID: 345336e72129
Revises: 0597a62d7f4c
Create Date: 2019-08-19 21:27:20.942483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345336e72129'
down_revision = '0597a62d7f4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features_association',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('feature_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('features', sa.Column('name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_features_name'), 'features', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_features_name'), table_name='features')
    op.drop_column('features', 'name')
    op.drop_table('features_association')
    # ### end Alembic commands ###
