"""new images2

Revision ID: 4234ad301976
Revises: c4907c62dabf
Create Date: 2019-08-14 15:37:20.099470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4234ad301976'
down_revision = 'c4907c62dabf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('condition', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'condition')
    # ### end Alembic commands ###
