"""empty message

Revision ID: 48c95afd88ab
Revises: e62479a12a6c
Create Date: 2019-10-31 13:00:02.537030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c95afd88ab'
down_revision = 'e62479a12a6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('price', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'price')
    # ### end Alembic commands ###
