"""empty message

Revision ID: 60d5c27c4490
Revises: 
Create Date: 2020-02-15 22:13:21.672710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d5c27c4490'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bazaars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('color', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bazaars_created_at'), 'bazaars', ['created_at'], unique=False)
    op.create_index(op.f('ix_bazaars_updated_at'), 'bazaars', ['updated_at'], unique=False)
    op.create_table('birds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_birds_description'), 'birds', ['description'], unique=False)
    op.create_index(op.f('ix_birds_image_url'), 'birds', ['image_url'], unique=False)
    op.create_index(op.f('ix_birds_name'), 'birds', ['name'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('image_url', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_image_url'), 'categories', ['image_url'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_index(op.f('ix_categories_status'), 'categories', ['status'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=64), nullable=True),
    sa.Column('client_type', sa.String(length=64), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=140), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_created_at'), 'clients', ['created_at'], unique=False)
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=False)
    op.create_index(op.f('ix_clients_phone_number'), 'clients', ['phone_number'], unique=False)
    op.create_table('contact_us',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone_number', sa.String(length=120), nullable=True),
    sa.Column('message', sa.String(length=120), nullable=True),
    sa.Column('subject', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_us_created_at'), 'contact_us', ['created_at'], unique=False)
    op.create_index(op.f('ix_contact_us_updated_at'), 'contact_us', ['updated_at'], unique=False)
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avator', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_features_avator'), 'features', ['avator'], unique=False)
    op.create_index(op.f('ix_features_name'), 'features', ['name'], unique=False)
    op.create_table('fuel_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('makes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('image_url', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=10000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_makes_image_url'), 'makes', ['image_url'], unique=False)
    op.create_index(op.f('ix_makes_name'), 'makes', ['name'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('index', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('single_car_enquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget', sa.String(length=80), nullable=True),
    sa.Column('message', sa.String(length=200), nullable=True),
    sa.Column('make', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('phone_number', sa.String(length=80), nullable=True),
    sa.Column('plate', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('year', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_single_car_enquiries_created_at'), 'single_car_enquiries', ['created_at'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=64), nullable=True),
    sa.Column('supplier_type', sa.String(length=64), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=140), nullable=True),
    sa.Column('bank_name', sa.String(length=64), nullable=True),
    sa.Column('bank_country', sa.String(length=64), nullable=True),
    sa.Column('bank_address', sa.String(length=120), nullable=True),
    sa.Column('account_number', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_created_at'), 'suppliers', ['created_at'], unique=False)
    op.create_index(op.f('ix_suppliers_email'), 'suppliers', ['email'], unique=False)
    op.create_index(op.f('ix_suppliers_phone_number'), 'suppliers', ['phone_number'], unique=False)
    op.create_table('transmissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_name', sa.String(length=64), nullable=True),
    sa.Column('bill_no', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'rejected', 'approved', name='status_types', native_enum=False), server_default='pending', nullable=True),
    sa.Column('date_issued', sa.DateTime(), nullable=True),
    sa.Column('date_due', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bills_created_at'), 'bills', ['created_at'], unique=False)
    op.create_index(op.f('ix_bills_date_due'), 'bills', ['date_due'], unique=False)
    op.create_index(op.f('ix_bills_date_issued'), 'bills', ['date_issued'], unique=False)
    op.create_index(op.f('ix_bills_status'), 'bills', ['status'], unique=False)
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=10000), nullable=True),
    sa.Column('image_url', sa.String(length=64), nullable=True),
    sa.Column('make_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['make_id'], ['makes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_image_url'), 'models', ['image_url'], unique=False)
    op.create_index(op.f('ix_models_make_id'), 'models', ['make_id'], unique=False)
    op.create_index(op.f('ix_models_name'), 'models', ['name'], unique=False)
    op.create_table('quotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_name', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('quotation_no', sa.String(length=140), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'rejected', 'approved', name='status_types', native_enum=False), server_default='pending', nullable=True),
    sa.Column('quotation_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotations_created_at'), 'quotations', ['created_at'], unique=False)
    op.create_index(op.f('ix_quotations_quotation_date'), 'quotations', ['quotation_date'], unique=False)
    op.create_index(op.f('ix_quotations_status'), 'quotations', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('photo', sa.String(length=100), nullable=True),
    sa.Column('social_id', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('phone_number_personal', sa.String(length=100), nullable=True),
    sa.Column('phone_number_company', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('company_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('last_message_read_time', sa.DateTime(), nullable=True),
    sa.Column('last_booking_read_time', sa.DateTime(), nullable=True),
    sa.Column('last_offer_read_time', sa.DateTime(), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_company_name'), 'users', ['company_name'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_index(op.f('ix_users_token'), 'users', ['token'], unique=True)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=120), nullable=True),
    sa.Column('overview', sa.String(length=2000), nullable=True),
    sa.Column('paypal', sa.String(length=120), nullable=True),
    sa.Column('logo', sa.String(length=120), nullable=True),
    sa.Column('banner', sa.String(length=120), nullable=True),
    sa.Column('facebook', sa.String(length=120), nullable=True),
    sa.Column('twitter', sa.String(length=120), nullable=True),
    sa.Column('instagram', sa.String(length=120), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_no', sa.String(length=64), nullable=True),
    sa.Column('date_issued', sa.DateTime(), nullable=True),
    sa.Column('date_due', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'rejected', 'approved', name='status_types', native_enum=False), server_default='pending', nullable=True),
    sa.Column('quotation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_created_at'), 'invoices', ['created_at'], unique=False)
    op.create_index(op.f('ix_invoices_date_issued'), 'invoices', ['date_issued'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_body'), 'messages', ['body'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('payload_json', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_payload_json'), 'notifications', ['payload_json'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('total_price_adults', sa.Numeric(), nullable=True),
    sa.Column('total_price_children', sa.Numeric(), nullable=True),
    sa.Column('price_per_day_children', sa.Numeric(), nullable=True),
    sa.Column('price_per_day_adults', sa.Numeric(), nullable=True),
    sa.Column('publisher_id', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['publisher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(length=64), nullable=True),
    sa.Column('size', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('quotation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publishers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=120), nullable=True),
    sa.Column('overview', sa.String(length=2000), nullable=True),
    sa.Column('paypal', sa.String(length=120), nullable=True),
    sa.Column('logo', sa.String(length=120), nullable=True),
    sa.Column('banner', sa.String(length=120), nullable=True),
    sa.Column('facebook', sa.String(length=120), nullable=True),
    sa.Column('twitter', sa.String(length=120), nullable=True),
    sa.Column('instagram', sa.String(length=120), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('overal_ratings', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sellers_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('price', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('plate', sa.String(length=80), nullable=True),
    sa.Column('year', sa.String(length=80), nullable=True),
    sa.Column('mileage', sa.String(length=80), nullable=True),
    sa.Column('condition', sa.String(length=80), nullable=True),
    sa.Column('color', sa.String(length=80), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('make_id', sa.Integer(), nullable=True),
    sa.Column('seller_name', sa.String(length=80), nullable=True),
    sa.Column('seller_email', sa.String(length=80), nullable=True),
    sa.Column('phone_number', sa.String(length=80), nullable=True),
    sa.Column('area', sa.String(length=80), nullable=True),
    sa.Column('fuel_type_id', sa.Integer(), nullable=True),
    sa.Column('transmission_id', sa.Integer(), nullable=True),
    sa.Column('engine_size', sa.String(length=80), nullable=True),
    sa.Column('interior', sa.String(length=80), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fuel_type_id'], ['fuel_types.id'], ),
    sa.ForeignKeyConstraint(['make_id'], ['makes.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['transmission_id'], ['transmissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sellers_vehicles_area'), 'sellers_vehicles', ['area'], unique=False)
    op.create_index(op.f('ix_sellers_vehicles_color'), 'sellers_vehicles', ['color'], unique=False)
    op.create_index(op.f('ix_sellers_vehicles_condition'), 'sellers_vehicles', ['condition'], unique=False)
    op.create_index(op.f('ix_sellers_vehicles_description'), 'sellers_vehicles', ['description'], unique=False)
    op.create_index(op.f('ix_sellers_vehicles_engine_size'), 'sellers_vehicles', ['engine_size'], unique=False)
    op.create_index(op.f('ix_sellers_vehicles_fuel_type_id'), 'sellers_vehicles', ['fuel_type_id'], unique=False)
    op.create_index(op.f('ix_sellers_vehicles_interior'), 'sellers_vehicles', ['interior'], unique=False)
    op.create_index(op.f('ix_sellers_vehicles_make_id'), 'sellers_vehicles', ['make_id'], unique=False)
    op.create_index(op.f('ix_sellers_vehicles_mileage'), 'sellers_vehicles', ['mileage'], unique=False)
    op.create_index(op.f('ix_sellers_vehicles_model_id'), 'sellers_vehicles', ['model_id'], unique=False)
    op.create_index(op.f('ix_sellers_vehicles_name'), 'sellers_vehicles', ['name'], unique=False)
    op.create_index(op.f('ix_sellers_vehicles_phone_number'), 'sellers_vehicles', ['phone_number'], unique=False)
    op.create_index(op.f('ix_sellers_vehicles_plate'), 'sellers_vehicles', ['plate'], unique=False)
    op.create_index(op.f('ix_sellers_vehicles_price'), 'sellers_vehicles', ['price'], unique=False)
    op.create_index(op.f('ix_sellers_vehicles_seller_email'), 'sellers_vehicles', ['seller_email'], unique=False)
    op.create_index(op.f('ix_sellers_vehicles_seller_name'), 'sellers_vehicles', ['seller_name'], unique=False)
    op.create_index(op.f('ix_sellers_vehicles_year'), 'sellers_vehicles', ['year'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('plate', sa.String(length=80), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=True),
    sa.Column('image_url', sa.String(length=64), nullable=True),
    sa.Column('front_image_url', sa.String(length=64), nullable=True),
    sa.Column('back_image_url', sa.String(length=64), nullable=True),
    sa.Column('right_image_url', sa.String(length=64), nullable=True),
    sa.Column('left_image_url', sa.String(length=64), nullable=True),
    sa.Column('dash_image_url', sa.String(length=64), nullable=True),
    sa.Column('interior_image_url', sa.String(length=64), nullable=True),
    sa.Column('extra_images_url', sa.String(length=500), nullable=True),
    sa.Column('mileage', sa.String(length=80), nullable=True),
    sa.Column('condition', sa.String(length=80), nullable=True),
    sa.Column('color', sa.String(length=80), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('make_id', sa.Integer(), nullable=True),
    sa.Column('seller_name', sa.String(length=80), nullable=True),
    sa.Column('seller_email', sa.String(length=80), nullable=True),
    sa.Column('phone_number', sa.String(length=80), nullable=True),
    sa.Column('area', sa.String(length=80), nullable=True),
    sa.Column('fuel_type_id', sa.Integer(), nullable=True),
    sa.Column('transmission_id', sa.Integer(), nullable=True),
    sa.Column('engine_size', sa.String(length=80), nullable=True),
    sa.Column('interior', sa.String(length=80), nullable=True),
    sa.Column('bazaar_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bazaar_id'], ['bazaars.id'], ),
    sa.ForeignKeyConstraint(['fuel_type_id'], ['fuel_types.id'], ),
    sa.ForeignKeyConstraint(['make_id'], ['makes.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['transmission_id'], ['transmissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_area'), 'vehicles', ['area'], unique=False)
    op.create_index(op.f('ix_vehicles_back_image_url'), 'vehicles', ['back_image_url'], unique=False)
    op.create_index(op.f('ix_vehicles_color'), 'vehicles', ['color'], unique=False)
    op.create_index(op.f('ix_vehicles_condition'), 'vehicles', ['condition'], unique=False)
    op.create_index(op.f('ix_vehicles_dash_image_url'), 'vehicles', ['dash_image_url'], unique=False)
    op.create_index(op.f('ix_vehicles_description'), 'vehicles', ['description'], unique=False)
    op.create_index(op.f('ix_vehicles_engine_size'), 'vehicles', ['engine_size'], unique=False)
    op.create_index(op.f('ix_vehicles_featured'), 'vehicles', ['featured'], unique=False)
    op.create_index(op.f('ix_vehicles_front_image_url'), 'vehicles', ['front_image_url'], unique=False)
    op.create_index(op.f('ix_vehicles_fuel_type_id'), 'vehicles', ['fuel_type_id'], unique=False)
    op.create_index(op.f('ix_vehicles_image_url'), 'vehicles', ['image_url'], unique=False)
    op.create_index(op.f('ix_vehicles_interior'), 'vehicles', ['interior'], unique=False)
    op.create_index(op.f('ix_vehicles_interior_image_url'), 'vehicles', ['interior_image_url'], unique=False)
    op.create_index(op.f('ix_vehicles_left_image_url'), 'vehicles', ['left_image_url'], unique=False)
    op.create_index(op.f('ix_vehicles_make_id'), 'vehicles', ['make_id'], unique=False)
    op.create_index(op.f('ix_vehicles_mileage'), 'vehicles', ['mileage'], unique=False)
    op.create_index(op.f('ix_vehicles_model_id'), 'vehicles', ['model_id'], unique=False)
    op.create_index(op.f('ix_vehicles_name'), 'vehicles', ['name'], unique=False)
    op.create_index(op.f('ix_vehicles_phone_number'), 'vehicles', ['phone_number'], unique=False)
    op.create_index(op.f('ix_vehicles_plate'), 'vehicles', ['plate'], unique=False)
    op.create_index(op.f('ix_vehicles_right_image_url'), 'vehicles', ['right_image_url'], unique=False)
    op.create_index(op.f('ix_vehicles_seller_email'), 'vehicles', ['seller_email'], unique=False)
    op.create_index(op.f('ix_vehicles_seller_name'), 'vehicles', ['seller_name'], unique=False)
    op.create_table('Publocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('make', sa.String(length=120), nullable=True),
    sa.Column('publisher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Numeric(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enquiries_created_at'), 'enquiries', ['created_at'], unique=False)
    op.create_table('features_association',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('feature_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('price', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('plate', sa.String(length=80), nullable=True),
    sa.Column('year', sa.String(length=80), nullable=True),
    sa.Column('mileage', sa.String(length=80), nullable=True),
    sa.Column('condition', sa.String(length=80), nullable=True),
    sa.Column('color', sa.String(length=80), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('make_id', sa.Integer(), nullable=True),
    sa.Column('importer_name', sa.String(length=80), nullable=True),
    sa.Column('importer_email', sa.String(length=80), nullable=True),
    sa.Column('phone_number', sa.String(length=80), nullable=True),
    sa.Column('area', sa.String(length=80), nullable=True),
    sa.Column('fuel_type_id', sa.Integer(), nullable=True),
    sa.Column('transmission_id', sa.Integer(), nullable=True),
    sa.Column('engine_size', sa.String(length=80), nullable=True),
    sa.Column('interior', sa.String(length=80), nullable=True),
    sa.Column('budget', sa.Numeric(), nullable=True),
    sa.Column('transmission', sa.String(length=64), nullable=True),
    sa.Column('fuel', sa.String(length=64), nullable=True),
    sa.Column('test', sa.String(length=64), nullable=True),
    sa.Column('engine', sa.String(length=64), nullable=True),
    sa.Column('special_features', sa.String(length=2000), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['fuel_type_id'], ['fuel_types.id'], ),
    sa.ForeignKeyConstraint(['make_id'], ['makes.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['transmission_id'], ['transmissions.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imports_area'), 'imports', ['area'], unique=False)
    op.create_index(op.f('ix_imports_color'), 'imports', ['color'], unique=False)
    op.create_index(op.f('ix_imports_condition'), 'imports', ['condition'], unique=False)
    op.create_index(op.f('ix_imports_created_at'), 'imports', ['created_at'], unique=False)
    op.create_index(op.f('ix_imports_description'), 'imports', ['description'], unique=False)
    op.create_index(op.f('ix_imports_engine_size'), 'imports', ['engine_size'], unique=False)
    op.create_index(op.f('ix_imports_fuel_type_id'), 'imports', ['fuel_type_id'], unique=False)
    op.create_index(op.f('ix_imports_importer_email'), 'imports', ['importer_email'], unique=False)
    op.create_index(op.f('ix_imports_importer_name'), 'imports', ['importer_name'], unique=False)
    op.create_index(op.f('ix_imports_interior'), 'imports', ['interior'], unique=False)
    op.create_index(op.f('ix_imports_make_id'), 'imports', ['make_id'], unique=False)
    op.create_index(op.f('ix_imports_mileage'), 'imports', ['mileage'], unique=False)
    op.create_index(op.f('ix_imports_model_id'), 'imports', ['model_id'], unique=False)
    op.create_index(op.f('ix_imports_name'), 'imports', ['name'], unique=False)
    op.create_index(op.f('ix_imports_phone_number'), 'imports', ['phone_number'], unique=False)
    op.create_index(op.f('ix_imports_plate'), 'imports', ['plate'], unique=False)
    op.create_index(op.f('ix_imports_price'), 'imports', ['price'], unique=False)
    op.create_index(op.f('ix_imports_year'), 'imports', ['year'], unique=False)
    op.create_table('includes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('include', sa.String(length=120), nullable=True),
    sa.Column('price_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['price_id'], ['prices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('short_description', sa.String(length=320), nullable=True),
    sa.Column('long_description', sa.String(length=2000), nullable=True),
    sa.Column('publisher_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('package', sa.String(length=64), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('overal_ratings', sa.Integer(), nullable=True),
    sa.Column('connectivity', sa.String(length=120), nullable=True),
    sa.Column('physical_condition', sa.String(length=64), nullable=True),
    sa.Column('price_type_id', sa.Integer(), nullable=True),
    sa.Column('availability_from', sa.DateTime(), nullable=True),
    sa.Column('availability_to', sa.DateTime(), nullable=True),
    sa.Column('feature_id', sa.Integer(), nullable=True),
    sa.Column('add_ons', sa.String(length=2000), nullable=True),
    sa.Column('policy', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('space', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.ForeignKeyConstraint(['price_type_id'], ['prices.id'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_availability_from'), 'listings', ['availability_from'], unique=False)
    op.create_index(op.f('ix_listings_availability_to'), 'listings', ['availability_to'], unique=False)
    op.create_index(op.f('ix_listings_location'), 'listings', ['location'], unique=False)
    op.create_index(op.f('ix_listings_package'), 'listings', ['package'], unique=False)
    op.create_index(op.f('ix_listings_published'), 'listings', ['published'], unique=False)
    op.create_index(op.f('ix_listings_status'), 'listings', ['status'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=2000), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'rejected', 'approved', name='status_types', native_enum=False), server_default='pending', nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('payment_mode', sa.Enum('cash', 'cheque', 'online-payment', name='payment_mode', native_enum=False), server_default='cash', nullable=True),
    sa.Column('payment_type', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_payment_date'), 'payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_payments_payment_mode'), 'payments', ['payment_mode'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('pubemails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('publisher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pubphones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=120), nullable=True),
    sa.Column('publisher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tradein',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('phone_number', sa.String(length=64), nullable=True),
    sa.Column('transmission', sa.String(length=64), nullable=True),
    sa.Column('mileage', sa.String(length=64), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('vin', sa.String(length=64), nullable=True),
    sa.Column('image', sa.String(length=64), nullable=True),
    sa.Column('exterior_color', sa.String(length=64), nullable=True),
    sa.Column('interior_color', sa.String(length=64), nullable=True),
    sa.Column('exterior_condition', sa.String(length=64), nullable=True),
    sa.Column('interior_condition', sa.String(length=64), nullable=True),
    sa.Column('accident', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('comments', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tradein_created_at'), 'tradein', ['created_at'], unique=False)
    op.create_index(op.f('ix_tradein_email'), 'tradein', ['email'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity', sa.String(length=120), nullable=True),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_table('days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('day_by_day', sa.String(length=2000), nullable=True),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('image_url', sa.String(length=64), nullable=True),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_image_url'), 'images', ['image_url'], unique=False)
    op.create_index(op.f('ix_images_name'), 'images', ['name'], unique=False)
    op.create_table('listing_tags',
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], )
    )
    op.create_table('places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place', sa.String(length=120), nullable=True),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=64), nullable=True),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('publisher_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_comment'), 'reviews', ['comment'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price_id', sa.Integer(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['price_id'], ['prices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_description'), 'offers', ['description'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('children', sa.Integer(), nullable=True),
    sa.Column('adults', sa.Integer(), nullable=True),
    sa.Column('grand_total', sa.Numeric(), nullable=True),
    sa.Column('departure_date', sa.DateTime(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_index(op.f('ix_offers_description'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_reviews_comment'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_table('places')
    op.drop_table('listing_tags')
    op.drop_index(op.f('ix_images_name'), table_name='images')
    op.drop_index(op.f('ix_images_image_url'), table_name='images')
    op.drop_table('images')
    op.drop_table('days')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('activities')
    op.drop_index(op.f('ix_tradein_email'), table_name='tradein')
    op.drop_index(op.f('ix_tradein_created_at'), table_name='tradein')
    op.drop_table('tradein')
    op.drop_table('pubphones')
    op.drop_table('pubemails')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_mode'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_listings_status'), table_name='listings')
    op.drop_index(op.f('ix_listings_published'), table_name='listings')
    op.drop_index(op.f('ix_listings_package'), table_name='listings')
    op.drop_index(op.f('ix_listings_location'), table_name='listings')
    op.drop_index(op.f('ix_listings_availability_to'), table_name='listings')
    op.drop_index(op.f('ix_listings_availability_from'), table_name='listings')
    op.drop_table('listings')
    op.drop_table('includes')
    op.drop_index(op.f('ix_imports_year'), table_name='imports')
    op.drop_index(op.f('ix_imports_price'), table_name='imports')
    op.drop_index(op.f('ix_imports_plate'), table_name='imports')
    op.drop_index(op.f('ix_imports_phone_number'), table_name='imports')
    op.drop_index(op.f('ix_imports_name'), table_name='imports')
    op.drop_index(op.f('ix_imports_model_id'), table_name='imports')
    op.drop_index(op.f('ix_imports_mileage'), table_name='imports')
    op.drop_index(op.f('ix_imports_make_id'), table_name='imports')
    op.drop_index(op.f('ix_imports_interior'), table_name='imports')
    op.drop_index(op.f('ix_imports_importer_name'), table_name='imports')
    op.drop_index(op.f('ix_imports_importer_email'), table_name='imports')
    op.drop_index(op.f('ix_imports_fuel_type_id'), table_name='imports')
    op.drop_index(op.f('ix_imports_engine_size'), table_name='imports')
    op.drop_index(op.f('ix_imports_description'), table_name='imports')
    op.drop_index(op.f('ix_imports_created_at'), table_name='imports')
    op.drop_index(op.f('ix_imports_condition'), table_name='imports')
    op.drop_index(op.f('ix_imports_color'), table_name='imports')
    op.drop_index(op.f('ix_imports_area'), table_name='imports')
    op.drop_table('imports')
    op.drop_table('features_association')
    op.drop_index(op.f('ix_enquiries_created_at'), table_name='enquiries')
    op.drop_table('enquiries')
    op.drop_table('Publocations')
    op.drop_index(op.f('ix_vehicles_seller_name'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_seller_email'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_right_image_url'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_plate'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_phone_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_name'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_model_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_mileage'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_make_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_left_image_url'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_interior_image_url'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_interior'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_image_url'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_fuel_type_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_front_image_url'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_featured'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_engine_size'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_description'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_dash_image_url'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_condition'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_color'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_back_image_url'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_area'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_sellers_vehicles_year'), table_name='sellers_vehicles')
    op.drop_index(op.f('ix_sellers_vehicles_seller_name'), table_name='sellers_vehicles')
    op.drop_index(op.f('ix_sellers_vehicles_seller_email'), table_name='sellers_vehicles')
    op.drop_index(op.f('ix_sellers_vehicles_price'), table_name='sellers_vehicles')
    op.drop_index(op.f('ix_sellers_vehicles_plate'), table_name='sellers_vehicles')
    op.drop_index(op.f('ix_sellers_vehicles_phone_number'), table_name='sellers_vehicles')
    op.drop_index(op.f('ix_sellers_vehicles_name'), table_name='sellers_vehicles')
    op.drop_index(op.f('ix_sellers_vehicles_model_id'), table_name='sellers_vehicles')
    op.drop_index(op.f('ix_sellers_vehicles_mileage'), table_name='sellers_vehicles')
    op.drop_index(op.f('ix_sellers_vehicles_make_id'), table_name='sellers_vehicles')
    op.drop_index(op.f('ix_sellers_vehicles_interior'), table_name='sellers_vehicles')
    op.drop_index(op.f('ix_sellers_vehicles_fuel_type_id'), table_name='sellers_vehicles')
    op.drop_index(op.f('ix_sellers_vehicles_engine_size'), table_name='sellers_vehicles')
    op.drop_index(op.f('ix_sellers_vehicles_description'), table_name='sellers_vehicles')
    op.drop_index(op.f('ix_sellers_vehicles_condition'), table_name='sellers_vehicles')
    op.drop_index(op.f('ix_sellers_vehicles_color'), table_name='sellers_vehicles')
    op.drop_index(op.f('ix_sellers_vehicles_area'), table_name='sellers_vehicles')
    op.drop_table('sellers_vehicles')
    op.drop_table('publishers')
    op.drop_table('products')
    op.drop_table('prices')
    op.drop_index(op.f('ix_notifications_payload_json'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_messages_body'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_date_issued'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_created_at'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_table('customers')
    op.drop_index(op.f('ix_users_token'), table_name='users')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_company_name'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_quotations_status'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_quotation_date'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_created_at'), table_name='quotations')
    op.drop_table('quotations')
    op.drop_index(op.f('ix_models_name'), table_name='models')
    op.drop_index(op.f('ix_models_make_id'), table_name='models')
    op.drop_index(op.f('ix_models_image_url'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_bills_status'), table_name='bills')
    op.drop_index(op.f('ix_bills_date_issued'), table_name='bills')
    op.drop_index(op.f('ix_bills_date_due'), table_name='bills')
    op.drop_index(op.f('ix_bills_created_at'), table_name='bills')
    op.drop_table('bills')
    op.drop_table('transmissions')
    op.drop_index(op.f('ix_suppliers_phone_number'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_email'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_created_at'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_single_car_enquiries_created_at'), table_name='single_car_enquiries')
    op.drop_table('single_car_enquiries')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_makes_name'), table_name='makes')
    op.drop_index(op.f('ix_makes_image_url'), table_name='makes')
    op.drop_table('makes')
    op.drop_table('fuel_types')
    op.drop_index(op.f('ix_features_name'), table_name='features')
    op.drop_index(op.f('ix_features_avator'), table_name='features')
    op.drop_table('features')
    op.drop_index(op.f('ix_contact_us_updated_at'), table_name='contact_us')
    op.drop_index(op.f('ix_contact_us_created_at'), table_name='contact_us')
    op.drop_table('contact_us')
    op.drop_index(op.f('ix_clients_phone_number'), table_name='clients')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_index(op.f('ix_clients_created_at'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_categories_status'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_image_url'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_birds_name'), table_name='birds')
    op.drop_index(op.f('ix_birds_image_url'), table_name='birds')
    op.drop_index(op.f('ix_birds_description'), table_name='birds')
    op.drop_table('birds')
    op.drop_index(op.f('ix_bazaars_updated_at'), table_name='bazaars')
    op.drop_index(op.f('ix_bazaars_created_at'), table_name='bazaars')
    op.drop_table('bazaars')
    # ### end Alembic commands ###
