"""thirsty thursday

Revision ID: 65c8b804c2c2
Revises: 
Create Date: 2019-10-10 17:02:03.075766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65c8b804c2c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sellers_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('price', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('plate', sa.String(length=80), nullable=True),
    sa.Column('year', sa.String(length=80), nullable=True),
    sa.Column('mileage', sa.String(length=80), nullable=True),
    sa.Column('condition', sa.String(length=80), nullable=True),
    sa.Column('color', sa.String(length=80), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('make_id', sa.Integer(), nullable=True),
    sa.Column('seller_name', sa.String(length=80), nullable=True),
    sa.Column('seller_email', sa.String(length=80), nullable=True),
    sa.Column('phone_number', sa.String(length=80), nullable=True),
    sa.Column('area', sa.String(length=80), nullable=True),
    sa.Column('fuel_type_id', sa.Integer(), nullable=True),
    sa.Column('transmission_id', sa.Integer(), nullable=True),
    sa.Column('engine_size', sa.String(length=80), nullable=True),
    sa.Column('interior', sa.String(length=80), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fuel_type_id'], ['fuel_types.id'], ),
    sa.ForeignKeyConstraint(['make_id'], ['makes.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['transmission_id'], ['transmissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sellers_vehicles_area'), 'sellers_vehicles', ['area'], unique=False)
    op.create_index(op.f('ix_sellers_vehicles_color'), 'sellers_vehicles', ['color'], unique=False)
    op.create_index(op.f('ix_sellers_vehicles_condition'), 'sellers_vehicles', ['condition'], unique=False)
    op.create_index(op.f('ix_sellers_vehicles_description'), 'sellers_vehicles', ['description'], unique=False)
    op.create_index(op.f('ix_sellers_vehicles_engine_size'), 'sellers_vehicles', ['engine_size'], unique=False)
    op.create_index(op.f('ix_sellers_vehicles_fuel_type_id'), 'sellers_vehicles', ['fuel_type_id'], unique=False)
    op.create_index(op.f('ix_sellers_vehicles_interior'), 'sellers_vehicles', ['interior'], unique=False)
    op.create_index(op.f('ix_sellers_vehicles_make_id'), 'sellers_vehicles', ['make_id'], unique=False)
    op.create_index(op.f('ix_sellers_vehicles_mileage'), 'sellers_vehicles', ['mileage'], unique=False)
    op.create_index(op.f('ix_sellers_vehicles_model_id'), 'sellers_vehicles', ['model_id'], unique=False)
    op.create_index(op.f('ix_sellers_vehicles_name'), 'sellers_vehicles', ['name'], unique=False)
    op.create_index(op.f('ix_sellers_vehicles_phone_number'), 'sellers_vehicles', ['phone_number'], unique=False)
    op.create_index(op.f('ix_sellers_vehicles_plate'), 'sellers_vehicles', ['plate'], unique=False)
    op.create_index(op.f('ix_sellers_vehicles_price'), 'sellers_vehicles', ['price'], unique=False)
    op.create_index(op.f('ix_sellers_vehicles_seller_email'), 'sellers_vehicles', ['seller_email'], unique=False)
    op.create_index(op.f('ix_sellers_vehicles_seller_name'), 'sellers_vehicles', ['seller_name'], unique=False)
    op.create_index(op.f('ix_sellers_vehicles_year'), 'sellers_vehicles', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sellers_vehicles_year'), table_name='sellers_vehicles')
    op.drop_index(op.f('ix_sellers_vehicles_seller_name'), table_name='sellers_vehicles')
    op.drop_index(op.f('ix_sellers_vehicles_seller_email'), table_name='sellers_vehicles')
    op.drop_index(op.f('ix_sellers_vehicles_price'), table_name='sellers_vehicles')
    op.drop_index(op.f('ix_sellers_vehicles_plate'), table_name='sellers_vehicles')
    op.drop_index(op.f('ix_sellers_vehicles_phone_number'), table_name='sellers_vehicles')
    op.drop_index(op.f('ix_sellers_vehicles_name'), table_name='sellers_vehicles')
    op.drop_index(op.f('ix_sellers_vehicles_model_id'), table_name='sellers_vehicles')
    op.drop_index(op.f('ix_sellers_vehicles_mileage'), table_name='sellers_vehicles')
    op.drop_index(op.f('ix_sellers_vehicles_make_id'), table_name='sellers_vehicles')
    op.drop_index(op.f('ix_sellers_vehicles_interior'), table_name='sellers_vehicles')
    op.drop_index(op.f('ix_sellers_vehicles_fuel_type_id'), table_name='sellers_vehicles')
    op.drop_index(op.f('ix_sellers_vehicles_engine_size'), table_name='sellers_vehicles')
    op.drop_index(op.f('ix_sellers_vehicles_description'), table_name='sellers_vehicles')
    op.drop_index(op.f('ix_sellers_vehicles_condition'), table_name='sellers_vehicles')
    op.drop_index(op.f('ix_sellers_vehicles_color'), table_name='sellers_vehicles')
    op.drop_index(op.f('ix_sellers_vehicles_area'), table_name='sellers_vehicles')
    op.drop_table('sellers_vehicles')
    # ### end Alembic commands ###
