"""tuesday changes

Revision ID: 6945e0275903
Revises: a9b0513f1ca7
Create Date: 2019-10-15 14:24:29.531601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6945e0275903'
down_revision = 'a9b0513f1ca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('featured', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_vehicles_featured'), 'vehicles', ['featured'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_featured'), table_name='vehicles')
    op.drop_column('vehicles', 'featured')
    # ### end Alembic commands ###
