"""mare bana

Revision ID: 93608dc2518a
Revises: b2f38d020927
Create Date: 2019-08-06 18:25:36.903520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93608dc2518a'
down_revision = 'b2f38d020927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_models_name'), 'models', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_models_name'), table_name='models')
    op.drop_column('models', 'name')
    # ### end Alembic commands ###
