"""empty message

Revision ID: a5a834c486c6
Revises: f1092fd26c3e
Create Date: 2019-10-31 11:49:21.243418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5a834c486c6'
down_revision = 'f1092fd26c3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'year')
    # ### end Alembic commands ###
