"""thirsty thursday

Revision ID: a9b0513f1ca7
Revises: 65c8b804c2c2
Create Date: 2019-10-10 17:04:10.279451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9b0513f1ca7'
down_revision = '65c8b804c2c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('price', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('plate', sa.String(length=80), nullable=True),
    sa.Column('year', sa.String(length=80), nullable=True),
    sa.Column('mileage', sa.String(length=80), nullable=True),
    sa.Column('condition', sa.String(length=80), nullable=True),
    sa.Column('color', sa.String(length=80), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('make_id', sa.Integer(), nullable=True),
    sa.Column('seller_name', sa.String(length=80), nullable=True),
    sa.Column('seller_email', sa.String(length=80), nullable=True),
    sa.Column('phone_number', sa.String(length=80), nullable=True),
    sa.Column('area', sa.String(length=80), nullable=True),
    sa.Column('fuel_type_id', sa.Integer(), nullable=True),
    sa.Column('transmission_id', sa.Integer(), nullable=True),
    sa.Column('engine_size', sa.String(length=80), nullable=True),
    sa.Column('interior', sa.String(length=80), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fuel_type_id'], ['fuel_types.id'], ),
    sa.ForeignKeyConstraint(['make_id'], ['makes.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['transmission_id'], ['transmissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imports_area'), 'imports', ['area'], unique=False)
    op.create_index(op.f('ix_imports_color'), 'imports', ['color'], unique=False)
    op.create_index(op.f('ix_imports_condition'), 'imports', ['condition'], unique=False)
    op.create_index(op.f('ix_imports_description'), 'imports', ['description'], unique=False)
    op.create_index(op.f('ix_imports_engine_size'), 'imports', ['engine_size'], unique=False)
    op.create_index(op.f('ix_imports_fuel_type_id'), 'imports', ['fuel_type_id'], unique=False)
    op.create_index(op.f('ix_imports_interior'), 'imports', ['interior'], unique=False)
    op.create_index(op.f('ix_imports_make_id'), 'imports', ['make_id'], unique=False)
    op.create_index(op.f('ix_imports_mileage'), 'imports', ['mileage'], unique=False)
    op.create_index(op.f('ix_imports_model_id'), 'imports', ['model_id'], unique=False)
    op.create_index(op.f('ix_imports_name'), 'imports', ['name'], unique=False)
    op.create_index(op.f('ix_imports_phone_number'), 'imports', ['phone_number'], unique=False)
    op.create_index(op.f('ix_imports_plate'), 'imports', ['plate'], unique=False)
    op.create_index(op.f('ix_imports_price'), 'imports', ['price'], unique=False)
    op.create_index(op.f('ix_imports_seller_email'), 'imports', ['seller_email'], unique=False)
    op.create_index(op.f('ix_imports_seller_name'), 'imports', ['seller_name'], unique=False)
    op.create_index(op.f('ix_imports_year'), 'imports', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_imports_year'), table_name='imports')
    op.drop_index(op.f('ix_imports_seller_name'), table_name='imports')
    op.drop_index(op.f('ix_imports_seller_email'), table_name='imports')
    op.drop_index(op.f('ix_imports_price'), table_name='imports')
    op.drop_index(op.f('ix_imports_plate'), table_name='imports')
    op.drop_index(op.f('ix_imports_phone_number'), table_name='imports')
    op.drop_index(op.f('ix_imports_name'), table_name='imports')
    op.drop_index(op.f('ix_imports_model_id'), table_name='imports')
    op.drop_index(op.f('ix_imports_mileage'), table_name='imports')
    op.drop_index(op.f('ix_imports_make_id'), table_name='imports')
    op.drop_index(op.f('ix_imports_interior'), table_name='imports')
    op.drop_index(op.f('ix_imports_fuel_type_id'), table_name='imports')
    op.drop_index(op.f('ix_imports_engine_size'), table_name='imports')
    op.drop_index(op.f('ix_imports_description'), table_name='imports')
    op.drop_index(op.f('ix_imports_condition'), table_name='imports')
    op.drop_index(op.f('ix_imports_color'), table_name='imports')
    op.drop_index(op.f('ix_imports_area'), table_name='imports')
    op.drop_table('imports')
    # ### end Alembic commands ###
