"""monday bl

Revision ID: b58a62629150
Revises: ad98f34ba557
Create Date: 2019-08-19 15:29:52.952021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b58a62629150'
down_revision = 'ad98f34ba557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vehicles_engine_size', table_name='vehicles')
    op.drop_column('vehicles', 'engine_size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('engine_size', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.create_index('ix_vehicles_engine_size', 'vehicles', ['engine_size'], unique=False)
    # ### end Alembic commands ###
