"""new images

Revision ID: c4907c62dabf
Revises: 93608dc2518a
Create Date: 2019-08-14 13:54:41.113156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4907c62dabf'
down_revision = '93608dc2518a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('back_image_url', sa.String(length=64), nullable=True))
    op.add_column('vehicles', sa.Column('dash_image_url', sa.String(length=64), nullable=True))
    op.add_column('vehicles', sa.Column('front_image_url', sa.String(length=64), nullable=True))
    op.add_column('vehicles', sa.Column('interior_image_url', sa.String(length=64), nullable=True))
    op.add_column('vehicles', sa.Column('left_image_url', sa.String(length=64), nullable=True))
    op.add_column('vehicles', sa.Column('right_image_url', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_vehicles_back_image_url'), 'vehicles', ['back_image_url'], unique=False)
    op.create_index(op.f('ix_vehicles_dash_image_url'), 'vehicles', ['dash_image_url'], unique=False)
    op.create_index(op.f('ix_vehicles_front_image_url'), 'vehicles', ['front_image_url'], unique=False)
    op.create_index(op.f('ix_vehicles_interior_image_url'), 'vehicles', ['interior_image_url'], unique=False)
    op.create_index(op.f('ix_vehicles_left_image_url'), 'vehicles', ['left_image_url'], unique=False)
    op.create_index(op.f('ix_vehicles_right_image_url'), 'vehicles', ['right_image_url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_right_image_url'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_left_image_url'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_interior_image_url'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_front_image_url'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_dash_image_url'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_back_image_url'), table_name='vehicles')
    op.drop_column('vehicles', 'right_image_url')
    op.drop_column('vehicles', 'left_image_url')
    op.drop_column('vehicles', 'interior_image_url')
    op.drop_column('vehicles', 'front_image_url')
    op.drop_column('vehicles', 'dash_image_url')
    op.drop_column('vehicles', 'back_image_url')
    # ### end Alembic commands ###
