"""friyay

Revision ID: c6ec235055f5
Revises: 11ac536222f7
Create Date: 2019-08-16 14:42:45.980110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6ec235055f5'
down_revision = '11ac536222f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('area', sa.String(length=80), nullable=True))
    op.add_column('vehicles', sa.Column('phone_number', sa.String(length=80), nullable=True))
    op.add_column('vehicles', sa.Column('seller_email', sa.String(length=80), nullable=True))
    op.add_column('vehicles', sa.Column('seller_name', sa.String(length=80), nullable=True))
    op.create_index(op.f('ix_vehicles_area'), 'vehicles', ['area'], unique=False)
    op.create_index(op.f('ix_vehicles_phone_number'), 'vehicles', ['phone_number'], unique=False)
    op.create_index(op.f('ix_vehicles_seller_email'), 'vehicles', ['seller_email'], unique=False)
    op.create_index(op.f('ix_vehicles_seller_name'), 'vehicles', ['seller_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_seller_name'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_seller_email'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_phone_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_area'), table_name='vehicles')
    op.drop_column('vehicles', 'seller_name')
    op.drop_column('vehicles', 'seller_email')
    op.drop_column('vehicles', 'phone_number')
    op.drop_column('vehicles', 'area')
    # ### end Alembic commands ###
