"""empty message

Revision ID: c922f91b47ae
Revises: 5807347092b7
Create Date: 2019-10-30 12:43:21.733678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c922f91b47ae'
down_revision = '5807347092b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('extra_images_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'extra_images_url')
    # ### end Alembic commands ###
