"""new images4

Revision ID: e5f295a21c7c
Revises: 24ca0775c66f
Create Date: 2019-08-14 17:35:00.350509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f295a21c7c'
down_revision = '24ca0775c66f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('name', sa.String(length=80), nullable=True))
    op.create_index(op.f('ix_vehicles_name'), 'vehicles', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_name'), table_name='vehicles')
    op.drop_column('vehicles', 'name')
    # ### end Alembic commands ###
