"""empty message

Revision ID: e62479a12a6c
Revises: a5a834c486c6
Create Date: 2019-10-31 12:59:12.508975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e62479a12a6c'
down_revision = 'a5a834c486c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vehicles_price', table_name='vehicles')
    op.drop_column('vehicles', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('price', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.create_index('ix_vehicles_price', 'vehicles', ['price'], unique=False)
    # ### end Alembic commands ###
