"""empty message

Revision ID: f1092fd26c3e
Revises: c922f91b47ae
Create Date: 2019-10-31 11:47:35.624524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1092fd26c3e'
down_revision = 'c922f91b47ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vehicles_year', table_name='vehicles')
    op.drop_column('vehicles', 'year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('year', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.create_index('ix_vehicles_year', 'vehicles', ['year'], unique=False)
    # ### end Alembic commands ###
